TOP=..
include $(TOP)/configure/CONFIG
#=======================================

DATA += heliox.proto
DATA += heliox_v.proto

DB += heliox.db
DB += heliox_channels.db
DB += heliox_regeneration.db

#=======================================
include $(TOP)/configure/RULES
